// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using libraryinfrastructure;

#nullable disable

namespace tournament_infrastructure.Migrations
{
    [DbContext(typeof(DbTournamentContext))]
    partial class DbTournamentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TournamentParticipation", b =>
                {
                    b.Property<string>("TournamentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tournament_name");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.HasKey("TournamentName", "TeamName")
                        .HasName("tournament_participation_pkey");

                    b.HasIndex("TeamName");

                    b.ToTable("tournament_participation", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Captain", b =>
                {
                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.HasKey("Nickname")
                        .HasName("captain_pkey");

                    b.HasIndex(new[] { "TeamName" }, "captain_team_name_key")
                        .IsUnique();

                    b.ToTable("captain", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("coach_pkey");

                    b.ToTable("coach", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("match_date");

                    b.Property<string>("Stage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stage");

                    b.Property<string>("TournamentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tournament_name");

                    b.Property<string>("WinnerTeam")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("winner_team");

                    b.HasKey("Id")
                        .HasName("match_pkey");

                    b.HasIndex("TournamentName");

                    b.HasIndex("WinnerTeam");

                    b.ToTable("match", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Organizer", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_email");

                    b.HasKey("Name")
                        .HasName("organizer_pkey");

                    b.ToTable("organizer", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Player", b =>
                {
                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nickname");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<string>("RealName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("real_name");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("SubstituteFor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("substitute_for");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.HasKey("Nickname")
                        .HasName("player_pkey");

                    b.HasIndex("SubstituteFor");

                    b.HasIndex("TeamName");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Sponsor", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_email");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Name")
                        .HasName("sponsor_pkey");

                    b.ToTable("sponsor", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Sponsorship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("EntityType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<string>("SponsorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sponsor_name");

                    b.HasKey("Id")
                        .HasName("sponsorship_pkey");

                    b.HasIndex("SponsorName");

                    b.ToTable("sponsorship", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Statistic", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_name");

                    b.Property<int?>("Damage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage");

                    b.Property<int?>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("deaths");

                    b.Property<int?>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kills");

                    b.HasKey("MatchId", "TeamName")
                        .HasName("statistics_pkey");

                    b.HasIndex("TeamName");

                    b.ToTable("statistics", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Team", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("CoachId")
                        .HasColumnType("integer")
                        .HasColumnName("coach_id");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<int?>("CreationYear")
                        .HasColumnType("integer")
                        .HasColumnName("creation_year");

                    b.Property<int?>("RankingPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ranking_points");

                    b.HasKey("Name")
                        .HasName("team_pkey");

                    b.HasIndex(new[] { "CoachId" }, "team_coach_id_key")
                        .IsUnique();

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.Tournament", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("OrganizerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organizer_name");

                    b.Property<decimal?>("PrizePool")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("prize_pool");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Name")
                        .HasName("tournament_pkey");

                    b.HasIndex("OrganizerName");

                    b.ToTable("tournament", (string)null);
                });

            modelBuilder.Entity("tournamentdomain.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("tournamentdomain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("tournamentdomain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tournamentdomain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("tournamentdomain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TournamentParticipation", b =>
                {
                    b.HasOne("tournamentdomain.Model.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tournament_participation_team_name_fkey");

                    b.HasOne("tournamentdomain.Model.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tournament_participation_tournament_name_fkey");
                });

            modelBuilder.Entity("tournamentdomain.Model.Captain", b =>
                {
                    b.HasOne("tournamentdomain.Model.Player", "NicknameNavigation")
                        .WithOne("Captain")
                        .HasForeignKey("tournamentdomain.Model.Captain", "Nickname")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("captain_nickname_fkey");

                    b.HasOne("tournamentdomain.Model.Team", "TeamNameNavigation")
                        .WithOne("Captain")
                        .HasForeignKey("tournamentdomain.Model.Captain", "TeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("captain_team_name_fkey");

                    b.Navigation("NicknameNavigation");

                    b.Navigation("TeamNameNavigation");
                });

            modelBuilder.Entity("tournamentdomain.Model.Match", b =>
                {
                    b.HasOne("tournamentdomain.Model.Tournament", "TournamentNameNavigation")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("match_tournament_name_fkey");

                    b.HasOne("tournamentdomain.Model.Team", "WinnerTeamNavigation")
                        .WithMany("Matches")
                        .HasForeignKey("WinnerTeam")
                        .HasConstraintName("match_winner_team_fkey");

                    b.Navigation("TournamentNameNavigation");

                    b.Navigation("WinnerTeamNavigation");
                });

            modelBuilder.Entity("tournamentdomain.Model.Player", b =>
                {
                    b.HasOne("tournamentdomain.Model.Player", "SubstituteForNavigation")
                        .WithMany("InverseSubstituteForNavigation")
                        .HasForeignKey("SubstituteFor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("player_substitute_for_fkey");

                    b.HasOne("tournamentdomain.Model.Team", "TeamNameNavigation")
                        .WithMany("Players")
                        .HasForeignKey("TeamName")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("player_team_name_fkey");

                    b.Navigation("SubstituteForNavigation");

                    b.Navigation("TeamNameNavigation");
                });

            modelBuilder.Entity("tournamentdomain.Model.Sponsorship", b =>
                {
                    b.HasOne("tournamentdomain.Model.Sponsor", "SponsorNameNavigation")
                        .WithMany("Sponsorships")
                        .HasForeignKey("SponsorName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("sponsorship_sponsor_name_fkey");

                    b.Navigation("SponsorNameNavigation");
                });

            modelBuilder.Entity("tournamentdomain.Model.Statistic", b =>
                {
                    b.HasOne("tournamentdomain.Model.Match", "Match")
                        .WithMany("Statistics")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("statistics_match_id_fkey");

                    b.HasOne("tournamentdomain.Model.Team", "TeamNameNavigation")
                        .WithMany("Statistics")
                        .HasForeignKey("TeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("statistics_team_name_fkey");

                    b.Navigation("Match");

                    b.Navigation("TeamNameNavigation");
                });

            modelBuilder.Entity("tournamentdomain.Model.Team", b =>
                {
                    b.HasOne("tournamentdomain.Model.Coach", "Coach")
                        .WithOne("Team")
                        .HasForeignKey("tournamentdomain.Model.Team", "CoachId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("team_coach_id_fkey");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("tournamentdomain.Model.Tournament", b =>
                {
                    b.HasOne("tournamentdomain.Model.Organizer", "OrganizerNameNavigation")
                        .WithMany("Tournaments")
                        .HasForeignKey("OrganizerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("tournament_organizer_name_fkey");

                    b.Navigation("OrganizerNameNavigation");
                });

            modelBuilder.Entity("tournamentdomain.Model.Coach", b =>
                {
                    b.Navigation("Team");
                });

            modelBuilder.Entity("tournamentdomain.Model.Match", b =>
                {
                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("tournamentdomain.Model.Organizer", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("tournamentdomain.Model.Player", b =>
                {
                    b.Navigation("Captain");

                    b.Navigation("InverseSubstituteForNavigation");
                });

            modelBuilder.Entity("tournamentdomain.Model.Sponsor", b =>
                {
                    b.Navigation("Sponsorships");
                });

            modelBuilder.Entity("tournamentdomain.Model.Team", b =>
                {
                    b.Navigation("Captain");

                    b.Navigation("Matches");

                    b.Navigation("Players");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("tournamentdomain.Model.Tournament", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
